name: Microservices CI

on:
  push:
    branches:
      - part2/microservices-project

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Build Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 4️⃣ Build all services
      - name: Build Docker Images
        run: docker-compose build

      # 5️⃣ Run tests for microservices
      - name: Test API Gateway
        run: docker-compose run --rm api-gateway npm test

      - name: Test Identity Service
        run: docker-compose run --rm identity-service npm test

      - name: Test Post Service
        run: docker-compose run --rm post-service npm test

      - name: Test Media Service
        run: docker-compose run --rm media-service npm test

      - name: Test Search Service
        run: docker-compose run --rm search-service npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Images
        run: |
          docker tag api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker tag identity-service:latest ${{ secrets.DOCKER_USERNAME }}/identity-service:latest
          docker tag post-service:latest ${{ secrets.DOCKER_USERNAME }}/post-service:latest
          docker tag media-service:latest ${{ secrets.DOCKER_USERNAME }}/media-service:latest
          docker tag search-service:latest ${{ secrets.DOCKER_USERNAME }}/search-service:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/identity-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/post-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/media-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/search-service:latest
